trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - 'old'
  paths:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'Cartomatic.Utils/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install nuget'
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'Nuget restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'Cartomatic.Utils'
    platform: '$(buildPlatform)'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'

- task: NuGetCommand@2
  displayName: 'Nuget pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*.Tests.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'
    includeSymbols: true

- task: NuGetCommand@2
  displayName: 'Nuget push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'c6740581-3eaf-4b5b-939e-0e756e6e280e'